
title: Julian San Diego
description: EE/EECS Undergraduate Researcher at UC Berkeley

navigation:
  - text: "Home"
    url: "/"
  - text: "Projects"
    url: "/portfolio/"
  - text: "Resume"
    url: "/resume/"
  